-- MySQL Script generated by MySQL Workbench
-- Sex 02 Jun 2017 21:30:04 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema votes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `votes` ;

-- -----------------------------------------------------
-- Schema votes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `votes` DEFAULT CHARACTER SET utf8 ;
