	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hackathon - UFBA</title>
    <link rel="stylesheet" href="bower_components/gaintime/css/gaintime.min.css" media ="screen" title="no title">
    <link rel="stylesheet" href="assets/css/hackathon.min.css" media ="screen" title="no title">